spring:
#  ssh:
#    tunnel:
#      host: 10.4.85.44
#      port: 22
#      username: sysadmin
#      password: sitern007
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
#    url: jdbc:mysql://localhost:3306/sitern
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://10.4.85.44:3306/SITern
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none



