spring:
#  ssh:
#    tunnel:
#      host: 10.4.85.44
#      port: 22
#      username: sysadmin
#      password: sitern007
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:
#    url: jdbc:mysql://localhost:3306/sitern
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: Jubby4400
    password: sitern007

#    url: jdbc:mysql://localhost:3306/sitern
    url: jdbc:mysql://10.4.85.44:3307/backup_SITern?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8

  #    url: jdbc:mysql://172.17.0.1:3307/New_SITern
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
jwt:
  secret: "mt9SzMnAbvffN4rWp/9XWHh9S8Di3xque3zBcfLJlbxPkAaiztunVfYETB2tV5grDGDc5w+0raj/
skHalDme0g=="
  refreshExpirationDateInMs: 600000
#ssh:
#  username: sysadmin
#  password: sitern007
#  host: 10.4.85.44
#  port: 22



