spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sitern007
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none



