spring:
  datasource:
    url: jdbc:mysql://10.4.85.44:3306/SITern
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sitern007
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  ssh:
#    tunnel:
#      host: 10.4.85.44
#      port: 22
#      username: sysadmin
#      password: sitern007



